### ISSUE TITLE
请问拆成两个配置文件怎么使用？

### ISSUE THREAD

**Issue by foxfire881** [learnhard-cn/free_proxy_ss#12]
我也认为拆成启动、更新两个配置文件比较合理，但是clash启动参数只能指定一个config文件，请问如果拆成两个配置文件（启动config.yaml、更新config.provider.yaml）要怎么使用？自己写脚本合并，然后再重启吗？

个人认为如果需要重启的话体验不太好（手动重启麻烦，自动重启容易中断翻墙体验）有没有什么热加载方案？

**Comment by Awkee** [comment]
参考俺写的vClash项目中的 [config.yaml](https://github.com/learnhard-cn/vClash/blob/ksmerlin386/clash/clash/config.yaml)配置方法，支持定期自动更新provider的，本地文件类型file/远端类型http 都支持的。
