### ISSUE TITLE
根本不会用啊，有谁能指导一下么？

### ISSUE THREAD

**Issue by lfglfg11** [learnhard-cn/free_proxy_ss#13]
clash-windows-amd64已经下载，就个脚本命令框
v2rayN-With-Core也已经下载，不会设置
源码也已下载。
这三个好像互不搭嘎，连不到一块去，到底咋用的？求个好心人给个教程，谢谢

**Comment by rev1ews** [comment]
这东西很简单啊，你什么终端系统



***@***.***
 
发件人： 轩辕北斗
发送时间： 2023-03-19 01:08
收件人： learnhard-cn/free_proxy_ss
抄送： Subscribed
主题： [learnhard-cn/free_proxy_ss] 根本不会用啊，有谁能指导一下么？ (Issue #13)
clash-windows-amd64已经下载，就个脚本命令框
v2rayN-With-Core也已经下载，不会设置
源码也已下载。
这三个好像互不搭嘎，连不到一块去，到底咋用的？求个好心人给个教程，谢谢

**Comment by lfglfg11** [comment]
> 这东西很简单啊，你什么终端系统 ***@***.*** 发件人： 轩辕北斗 发送时间： 2023-03-19 01:08 收件人： learnhard-cn/free_proxy_ss 抄送： 已订阅 主题： [learnhard-cn/free_proxy_ss] 根本不会用么啊，有谁能指导一下？ （问题 #13） clash-windows-amd64已经下载，就个脚本命令框 v2rayN-With-Core也已经下载，不会设置 源码也已下载。 这三个好像互不搭嘎，连不到一块去，到底咋用的？求个好心人给个教程，谢谢 — 直接回复此电子邮件，在 GitHub 上查看或取消订阅。 您收到此消息是因为您订阅了此线程。消息 ID：***@***.***>

我是64位win10系统，麻烦指导下，谢谢

**Comment by FaMiNiuZiDa** [comment]
用w10系统的虚拟机软件开个窗口，然后在虚拟机上面装个w系统，然后在香港或者东南亚随便买个服务器，用虚拟机系统登录连接服务器，然后把你的电脑跟虚拟机的网络串联到一块，
