### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by yangyang20** [learnhard-cn/free_proxy_ss#2]
我的云服务器在美国，，配置好v2ray之后却一直连接不上，同样的方法在香港的服务器却可行，网上的解决办法大都是说服务器时间不同步，我修改时区时间之后，却还是不行，，若您知道原因，请指导一下

**Comment by Awkee** [comment]
> 我的云服务器在美国，，配置好v2ray之后却一直连接不上，同样的方法在香港的服务器却可行，网上的解决办法大都是说服务器时间不同步，我修改时区时间之后，却还是不行，，若您知道原因，请指导一下

连接不上的问题比较多，需要耐心分析原因(**知道原因才能找到解决办法呀**)，一点点排除：

1. 检查从家里访问v2ray的TCP/UDP端口是否可以访问（排除防火墙导致无法访问）。
2. 确认SSH可以登录，排除IP地址被屏蔽情况。
3. v2ray客户端与服务器的时间不匹配，误差不能超过90秒钟；这个说的不是时区哦。

服务器执行`timedatectl`命令：
```bash
$ timedatectl 
               Local time: 五 2021-09-17 19:41:14 CST
           Universal time: 五 2021-09-17 11:41:14 UTC
                 RTC time: 五 2021-09-17 11:41:14    
                Time zone: Asia/Shanghai (CST, +0800)
System clock synchronized: yes                       
              NTP service: active                    
          RTC in local TZ: no
```

其中，UTC时间是格林威治时间，加上时区就是`Localtime`本地时间。 对比下这个`Local time`时间看看延迟多少吧。


Vray的常见问题检查地址：
https://www.v2ray.com/chapter_00/faq.html
