### ISSUE TITLE
不会用，别的地方的一个URL能搞定。

### ISSUE THREAD

**Issue by izhukai** [learnhard-cn/free_proxy_ss#3]
不会用，

从URL下载或者从导入您的代码
然后点配置里面的yaml，都报错，

还要自己改什么吗

别的地方的一个URL能搞定。

**Comment by Awkee** [comment]
你说的而别人的一个URL搞定！其实使用的是Clash完整的启动配置文件， 这里拆开来两个配置：启动配置+代理订阅配置。

`代理订阅文件clash.provider.yaml` 可以根据启动配置文件 `clash.yaml` 规则定期更新(目前因为访问github异常问题导致更新失败)
报错的原因很可能是本地网络无法访问github的链接导致的吧。

**Comment by izhukai** [comment]
所以，像我这种小白要怎么用呢，目前我只添加了 https://raw.githubusercontent.com/learnhard-cn/free_proxy_ss/main/clash/clash.provider.yaml








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "learnhard-cn/free_proxy_ss"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月15日(星期五) 下午3:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [learnhard-cn/free_proxy_ss] 不会用，别的地方的一个URL能搞定。 (#3)





 
你说的而别人的一个URL搞定！其实使用的是Clash完整的启动配置文件， 这里拆开来两个配置：启动配置+代理订阅配置。
 
代理订阅文件clash.provider.yaml 可以根据启动配置文件 clash.yaml 规则定期更新(目前因为访问github异常问题导致更新失败)
 报错的原因很可能是本地网络无法访问github的链接导致的吧。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by izhukai** [comment]
数据加载中...
