### ISSUE TITLE
ShadowSocksR 使用的 chacha20 加密算法在 clash v0.17.0 中被弃用

### ISSUE THREAD

**Issue by NightSpaceC** [learnhard-cn/free_proxy_ss#5]
如题，[https://github.com/Dreamacro/clash/releases/tag/v0.17.0](v0.17.0)
这使我无法正常使用您提供的节点，请问您正在使用什么客户端？
我使用的客户端是Clash Premium 2021.11.08

**Comment by Awkee** [comment]
preminum最新版本，废弃的算法就没做验证，也不太好加验证条件。
