### ISSUE TITLE
clash for android报错

### ISSUE THREAD

**Issue by DoveBoy** [learnhard-cn/free_proxy_ss#6]
[config.yaml](https://raw.githubusercontent.com/learnhard-cn/free_proxy_ss/main/config.yaml)配置到clash for android中报错无法使用，clash for windows正常使用，请兼容一下clash for android
![Screenshot_2021-12-10-21-21-38-63_1ed813789000d97ac1c6fc69779c1198](https://user-images.githubusercontent.com/19201447/145580486-c823502f-6af8-4a55-b632-966bea90d95f.jpg)

**Comment by Awkee** [comment]
使用新的 启动配置就可以了 ： [clash_url.yaml](https://raw.githubusercontent.com/learnhard-cn/free_proxy_ss/main/clash/clash_cdn.yaml)
